### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.engine'

### ISSUE THREAD

**Issue by Vaibhav170216** [ZFTurbo/classification_models_1D#2]
I was trying to use this classification_models library but while setting up the model for Resnet its showing "keras.engine" not found.
I have all the other necessary libraries installed.

Pls help.

**Comment by ZFTurbo** [comment]
Can you try install exactly this versions:

```
tensorflow==2.8.0
keras_applications==1.0.8
```

After please try to run:
https://github.com/ZFTurbo/classification_models_1D/blob/main/tst_1D_classification_tfkeras.py

**Comment by Vaibhav170216** [comment]
Hi, Thank you for the solution. The library seems to be working now but after training the model, the predict method seems to be taking a lot if time and not showing any progress and there is no error also.

**Comment by ZFTurbo** [comment]
> Hi, Thank you for the solution. The library seems to be working now but after training the model, the predict method seems to be taking a lot if time and not showing any progress and there is no error also.

Can you give more details on how you do the prediction?

**Comment by Vaibhav170216** [comment]
It worked thankfully, it was just taking a lot of time. But the predictions are not good, it seems model is overfitting. On the other hand my own cnn 1d model worked just fine.
